# -*- coding: utf-8 -*-
"""Python2_Anusha_Bellad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AG8mkttjjr-jqieJ9hwollPPBdkeVjW
"""

#Assignment to get the list of ingredients.

list_veg=["Tomato","Beet","Onion","Potato","Spinach","Mint"]
print("List of leafy vegetables is :", list_veg[4:])
print("List of red vegetables is :", list_veg[:2])


#assignment to get the marks.
list_marks= ['Tom', 90, 'Holly', 98, 'Jack', 70, 'Jill', 100]
print("List of Marks obtained is : " , list_marks[1::2])
print("List of Students is: ", list_marks[0::2])